### ISSUE TITLE
help needed / Face tracking issues on mobile phones

### ISSUE THREAD

**Issue by Qs-cic** [hiukim/mind-ar-js#149]
Face tracking cases cannot achieve the normal face tracking effect on mobile phones, especially android phones, hats, glasses and other models cannot follow the face to move. Please advise me to solve this problem to ensure that it works properly on mobile.

**Comment by hiukim** [comment]
@Qs-cic Can you provide more details on the issue? Maybe video capture or screenshot.

**Comment by buddy90210** [comment]
I have same problem, but not really same) face tracking is working good, but models positions are diferent on mobile phones and desktop camera, when i use "a-camera active="true"" it's works fine on  mobile, if active="false" on desktop camera.

**Comment by buddy90210** [comment]
And positions are diferent when using aframe or threejs.

**Comment by ismaelash** [comment]
Hello, 

i have like problem.
On iOS, faace tracking works fine generally, but on Android the tracking not start on position right

Regards,

**Comment by hiukim** [comment]
can provide any video capture or screenshot to show the problems?

**Comment by ismaelash** [comment]
> can provide any video capture or screenshot to show the problems?

Android example 1:
![face_android](https://user-images.githubusercontent.com/19227867/168337984-81d3406d-a3b4-4626-9c3f-8452ef3b07af.jpg)

Android example 2:
![face_android_2](https://user-images.githubusercontent.com/19227867/168337994-8435b2c8-8a44-444e-b1fa-75e1d0fe8012.jpeg)

iOS example 1:
![face_ios](https://user-images.githubusercontent.com/19227867/168338405-221f8f65-9dce-414c-8650-f9acfb3eb144.jpeg)

Web example:
![face_web](https://user-images.githubusercontent.com/19227867/168338006-df1dae99-c697-4f50-b214-ff18808c7d39.png)

**Comment by hiukim** [comment]
should be fixed v1.1.5

**Comment by fikry13** [comment]
Hi, sorry for resurrecting this, but I try it on 1.2 but the problem still exist on android
![image](https://user-images.githubusercontent.com/9731623/220836908-7e6c5a53-4cb3-4964-9fb2-6daba70b2f93.png)
