### ISSUE TITLE
[bug report] Face tracking not working properly on any Android browser

### ISSUE THREAD

**Issue by marcusx2** [hiukim/mind-ar-js#316]
There is a huge offset of the content that should appear on the face, it's way off. It doesn't work properly on any Android browser. It works just fine on all iPhone browsers though, even Safari and Edge.

Related [https://github.com/hiukim/mind-ar-js/issues/268](https://github.com/hiukim/mind-ar-js/issues/268)

**Comment by marcusx2** [comment]
@hiukim I wonder if this will be fixed? ;_;

**Comment by hiukim** [comment]
Hi, I can't really replicate this issue on my device.  I fixed something related in v1.1.5, but apparently it's not enough.

**Comment by marcusx2** [comment]
Can you tell me where the logic for your fix is located, and where the logic for the positioning is? I'll try to play around with it a bit and see if I can fix it myself and make a pull request.

**Comment by hiukim** [comment]
commits

https://github.com/hiukim/mind-ar-js/commit/ab4078203c42cdc7a9a10a9941824fac00dc8ff0

https://github.com/hiukim/mind-ar-js/commit/4cd09e9ce6cd54be216cca60cdcc303316b80e77

**Comment by realmigan** [comment]
I try different Android phones and it doesn't work properly on any Android browser.

**Comment by hiukim** [comment]
Can do screen recordings?

**Comment by marcusx2** [comment]
@hiukim where do you live? I can send you an android phone man xD

**Comment by hiukim** [comment]
haha, I'm using pixel 5 myself, and it looks good. LOL

**Comment by marcusx2** [comment]
Oh really? Try an old Samsung S8, which is the phone I'm using.

@realmigan can you tell us what android phones you tried on, just for reference? Let's make a list to make it easy for @hiukim , whichever phone of the list he can get his hands on will suffice.

**Comment by hiukim** [comment]
run `npm run build`

**Comment by marcusx2** [comment]
Hey man I just noticed that the fixes don't touch the `aframe.js` file, only the `three.js` one. Maybe that's the issue? You only applied the fix to the threejs version?

I've been trying to fix the problem to no avail ;_;

**Comment by hiukim** [comment]
Maybe I haven't fixed the aframe version. Does threeJS version working fine for you?

**Comment by marcusx2** [comment]
Yes man...the threejs version works. I can't believe this...it was working the whole time...the threejs version that is...can you fix the aframe version then? Thanks.

**Comment by hiukim** [comment]
nice. will fix that. thx

**Comment by hiukim** [comment]
@marcusx2 I finally can replicate this issue. I think this is resolved with the latest aframe version 1.4, e.g.

use

```
<script src="https://aframe.io/releases/1.4.1/aframe.min.js"></script>
```
instead of
```
<script src="https://aframe.io/releases/1.2.0/aframe.min.js"></script>
```

Can you verify?

**Comment by marcusx2** [comment]
@hiukim this didn't work. I still have the same problem when trying the [virtual try on example](https://hiukim.github.io/mind-ar-js-doc/face-tracking-samples/tryon.html). Can you reopen the ticket?

**Comment by marcusx2** [comment]
@hiukim if it helps at all, there's [this library](https://github.com/jeeliz/jeelizFaceFilter/tree/master/demos/aFrame/cube) with webar face tracking [using aframe](https://jeeliz.com/demos/faceFilter/demos/aFrame/cube/) where the issue doesn't happen. The answer to this problem can probably be found on their codebase..

**Comment by mayhemantt** [comment]
Is there any update regrading this issue?
i have tried a few things but doesn't seem to works

**Comment by hiukim** [comment]
maybe because missing `look-controls="enabled: false` in the camera entity. the example should have fixed now. 

Feel free to re-open the issue if not.

**Comment by marcusx2** [comment]
The offset is no longer there, but the models seem to be a lot bigger than they should be. The glasses are way bigger on Android devices.
