### ISSUE TITLE
cell phone sideways (rotate)

### ISSUE THREAD

**Issue by hbaugmentedreality** [hiukim/mind-ar-js#35]
Hi guys,
I'm pretty new with programing and this platform.  So, sorry for my basic question.
But I was trying the examples and when you put your cell phone sideways (rotate), the view is not correct anymore.  You can only see the camera image in the lowerleft corner of the browser.   The problem appears when you change from one orientation to another (vertical to horizontal for example). 
Here I attached an image.
Does it happen to you?   How can I solve this?
Thank you very much for your help.

![WhatsApp Image 2021-06-02 at 12 49 45](https://user-images.githubusercontent.com/73670108/120511753-11c1da00-c3a1-11eb-83b5-d2368e727eaf.jpeg)

**Comment by hiukim** [comment]
The library doesn't handle window rotation properly. Yes, definitely something need to be fixed.

**Comment by hbaugmentedreality** [comment]
Hi hiukim , thank for your answer.   Do you think you are going to fix it?  Is it complicate?  Thanks...

**Comment by hiukim** [comment]
Yes, I will fix it. sorry, I'm a bit occupied these days.

**Comment by hbaugmentedreality** [comment]
> Yes, I will fix it. sorry, I'm a bit occupied these days.

**Comment by hbaugmentedreality** [comment]
Thank you a lot @hiukim !!   Regards!!

**Comment by leonexcc** [comment]
Might be fixed by #83

**Comment by hiukim** [comment]
fixed in latest release.

**Comment by Virtualmerse** [comment]
Hello hiukim , thanks for such a great job. 

Quick note, I am afraid that the problem persists. I tested on Safari, Chrome and Firefox, using an iPhone.
